### ISSUE TITLE
Break apart the numeric line and the maze

### ISSUE THREAD

**Issue by lgraziani2712** [lgraziani2712/codimo#27]
Today we decided how we are going to manage the final-step-error.

Instead of "hackly" forcing a last and special block for entering the numeric line, we are going to make jump the number from the maze to the numeric line. So, if the number goes one step forward, it will fall from the maze.

This approach makes the `leave_maze` block more meaningful. And the user won't be feeling like it's being forced without logic to use that block.

### TODO

- [x] Change `leave_maze` description from "leave the maze" to "Jump".
- [x] Break apart the numeric line.
- [x] Test the number's position doesn't break if the numeric line has the new margin.
- [x] Create the falling animation.
- [x] Create the jumping effect.
- [x] Make the engine execute the new animation.
